name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  nf-test-stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: nf-core/setup-nextflow@v2
      - uses: nf-core/setup-nf-test@v1
      - name: nf-test (stub)
        run: nf-test test --tag stub
